/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leong.nimbus.gui;

import com.leong.nimbus.utils.Tools;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

/**
 *
 * @author henry
 */
public abstract class AbstractDialog extends javax.swing.JDialog
{
    protected DropTargetAdapter m_dropTarget;

    public AbstractDialog()
    {
        this(null);
    }

    public AbstractDialog(java.awt.Frame parent)
    {
        super(parent);
        initComponents();

        Tools.logit("AbstractDialog.ctor(window)");

        m_dropTarget = new DropTargetAdapter()
        {
            @Override
            public void drop(DropTargetDropEvent dtde)
            {
                action_drop(dtde);
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setTitle(String title)
    {
        final String APP_NAME = " - Nimbus";

        if (title.endsWith(APP_NAME))
            super.setTitle(title);
        else
            super.setTitle(title + APP_NAME);
    }

    public void runLater()
    {
        Tools.logit("AbstractDialog.runLater()");

        Runnable run = new Runnable()
        {
            @Override
            public void run()
            {
                do_run();
            }
        };

        java.awt.EventQueue.invokeLater(run);
    }

    public void runAndWait()
    {
        Tools.logit("AbstractDialog.runAndWait()");

        Runnable run = new Runnable()
        {
            @Override
            public void run()
            {
                do_run();
            }
        };

        try
        {
            Tools.logit("AbstractDialog.runAndWait() EventQueue.invokeAndWait(run)");
            java.awt.EventQueue.invokeAndWait(run);
            //SwingUtilities.invokeAndWait(run);
        }
        catch (InterruptedException ex)
        {
            //Logger.getLogger(AbstractJDialog.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("AbstractDialog.runAndWait() InterruptedException: "+ex.toString());
        }
        catch (InvocationTargetException ex)
        {
            //Logger.getLogger(AbstractJDialog.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("AbstractDialog.runAndWait() InvocationTargetException: "+ex.toString());
        }
    }

    protected void do_run()
    {
        //pack();
        //setModal(true);
        setVisible(true);
    }

    protected void action_windowOnClosing()
    {
        Tools.logit("AbstractDialog.action_windowOnClosing()");
    }

    protected void responsiveTaskUI()
    {
        // this call should be from another thread so the UI can be responsive
        // refer to class ResponsiveTaskUI
        try
        {
            // suspend this thread via sleep() and yeild control to other threads
            Thread.sleep(10);
        }
        catch (InterruptedException ex)
        {
            //Logger.getLogger(ResponsiveTaskUI.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("AbstractDialog.responsiveTaskUI() Thread.sleep() error: "+ex);
        }
    }

    protected void action_drop(DropTargetDropEvent dtde)
    {
        Tools.logit("AbstractDialog.action_drop()");

        // Accept copy drops
        dtde.acceptDrop(DnDConstants.ACTION_COPY);

        // Get the transfer which can provide the dropped item data
        Transferable transferable = dtde.getTransferable();

        // Get the data formats of the dropped item
        DataFlavor[] flavors = transferable.getTransferDataFlavors();

        // Loop through the flavors
        for (DataFlavor flavor : flavors)
        {
            try
            {
                // If the drop items are files
                if (flavor.isFlavorJavaFileListType())
                {
                    // Get all of the dropped files
                    final List files = (List) transferable.getTransferData(flavor);

                    ResponsiveTaskUI.doTask(new ResponsiveTaskUI.IResponsiveTask()
                    {
                        @Override
                        public void run()
                        {
                            onAction_drop(files);
                        }
                    });
                }
            }
            catch (Exception e)
            {
                // Print out the error stack
                e.printStackTrace();

            }
        }

        // Inform that the drop is complete
        dtde.dropComplete(true);
    }

    protected boolean onAction_drop(List objs)
    {
        return false;
    }
}
