/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leong.nimbus.gui;

import com.leong.nimbus.gui.helpers.ResponsiveTaskUI;
import com.leong.nimbus.mainapp.PickCloudDialog;
import com.leong.nimbus.utils.Tools;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

/**
 *
 * @author henry
 */
public class MyDialog extends javax.swing.JDialog
{
    protected PickCloudDialog m_picker;
    protected DropTargetAdapter m_dropTarget;

    public MyDialog()
    {
        this(null);
    }

    public MyDialog(java.awt.Frame parent)
    {
        super(parent);
        //initComponents();

        Tools.logit("MyDialog.ctor(window)");

        //setJMenuBar(mnuBar);

        m_dropTarget = new DropTargetAdapter()
        {
            @Override
            public void drop(DropTargetDropEvent dtde)
            {
                action_drop(dtde);
            }
        };
    }

    protected void super_initComponents()
    {
        initComponents();
        setJMenuBar(mnuBar);
    }

    public void setCloudPicker(PickCloudDialog picker)
    {
        m_picker = picker;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mnuBar = new javax.swing.JMenuBar();
        mnuNimbus = new javax.swing.JMenu();
        mnuNewCloud = new javax.swing.JMenuItem();

        mnuNimbus.setText("Nimbus");

        mnuNewCloud.setText("New Cloud");
        mnuNewCloud.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuNewCloudActionPerformed(evt);
            }
        });
        mnuNimbus.add(mnuNewCloud);

        mnuBar.add(mnuNimbus);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewCloudActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuNewCloudActionPerformed
    {//GEN-HEADEREND:event_mnuNewCloudActionPerformed
        if (m_picker == null)
        {
            Tools.logit("MyDialog.mnuNewCloudActionPerformed() No cloud picker...");
            return;
        }

        m_picker.setVisible(true);
        m_picker.requestFocus();
    }//GEN-LAST:event_mnuNewCloudActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuNewCloud;
    private javax.swing.JMenu mnuNimbus;
    // End of variables declaration//GEN-END:variables

    public void setTitle(String title)
    {
        final String APP_NAME = " - Nimbus";

        if (title.endsWith(APP_NAME))
            super.setTitle(title);
        else
            super.setTitle(title + APP_NAME);
    }

    public void runLater()
    {
        Tools.logit("MyDialog.runLater()");

        Runnable run = new Runnable()
        {
            @Override
            public void run()
            {
                do_run();
            }
        };

        java.awt.EventQueue.invokeLater(run);
    }

    public void runAndWait()
    {
        Tools.logit("MyDialog.runAndWait()");

        Runnable run = new Runnable()
        {
            @Override
            public void run()
            {
                do_run();
            }
        };

        try
        {
            Tools.logit("MyDialog.runAndWait() EventQueue.invokeAndWait(run)");
            java.awt.EventQueue.invokeAndWait(run);
            //SwingUtilities.invokeAndWait(run);
        }
        catch (InterruptedException ex)
        {
            //Logger.getLogger(AbstractJDialog.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("MyDialog.runAndWait() InterruptedException: "+ex.toString());
        }
        catch (InvocationTargetException ex)
        {
            //Logger.getLogger(AbstractJDialog.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("MyDialog.runAndWait() InvocationTargetException: "+ex.toString());
        }
    }

    protected void do_run()
    {
        //pack();
        //setModal(true);
        setVisible(true);
    }

    protected void action_windowOnClosing()
    {
        Tools.logit("MyDialog.action_windowOnClosing()");
    }

    protected void responsiveTaskUI()
    {
        // this call should be from another thread so the UI can be responsive
        // refer to class ResponsiveTaskUI
        try
        {
            // suspend this thread via sleep() and yeild control to other threads
            Thread.sleep(10);
        }
        catch (InterruptedException ex)
        {
            //Logger.getLogger(ResponsiveTaskUI.class.getName()).log(Level.SEVERE, null, ex);
            Tools.logit("MyDialog.responsiveTaskUI() Thread.sleep() error: "+ex);
        }
    }

    protected void action_drop(DropTargetDropEvent dtde)
    {
        Tools.logit("MyDialog.action_drop()");

        // Accept copy drops
        dtde.acceptDrop(DnDConstants.ACTION_COPY);

        // Get the transfer which can provide the dropped item data
        Transferable transferable = dtde.getTransferable();

        // Get the data formats of the dropped item
        DataFlavor[] flavors = transferable.getTransferDataFlavors();

        // Loop through the flavors
        for (DataFlavor flavor : flavors)
        {
            try
            {
                // If the drop items are files
                if (flavor.isFlavorJavaFileListType())
                {
                    // Get all of the dropped files
                    final List files = (List) transferable.getTransferData(flavor);

                    ResponsiveTaskUI.doTask(new ResponsiveTaskUI.IResponsiveTask()
                    {
                        @Override
                        public void run()
                        {
                            onAction_drop(files);
                        }
                    });
                }
            }
            catch (Exception e)
            {
                // Print out the error stack
                e.printStackTrace();

            }
        }

        // Inform that the drop is complete
        dtde.dropComplete(true);
    }

    protected boolean onAction_drop(List objs)
    {
        return false;
    }
}
