/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leong.nimbus.gui;

import com.leong.nimbus.utils.Logit;
import java.awt.CardLayout;
import java.lang.reflect.InvocationTargetException;

/**
 *
 * @author henry
 */
public class NimbusFrame extends javax.swing.JFrame
{
    public static enum CloudType
    {
        LOCAL_FILE_SYSTEM,
        GOOGLE_DRIVE,
        DROPBOX,
    }

    private static final Logit Log = Logit.create(NimbusFrame.class.getName());

    private final Runnable m_run;

    private final static String CARD_LOCAL_FILE_SYSTEM = "Local File System";
    private final static String CARD_GOOGLE_DRIVE = "Google Drive";
    private final static String CARD_DROPBOX = "Dropbox";

    /**
     * Creates new form NimbusFrame
     */
    public NimbusFrame()
    {
        Log.entering("<init>");
        initComponents();

        m_run = new Runnable()
        {
            @Override
            public void run()
            {
                setVisible(true);
            }
        };
    }

    public static NimbusFrame setupMainPanel(CloudType type)
    {
        NimbusFrame frame = new NimbusFrame();
        String cardName = "";

        switch (type)
        {
            case LOCAL_FILE_SYSTEM:
                cardName = CARD_LOCAL_FILE_SYSTEM;
                break;

            case GOOGLE_DRIVE:
                cardName = CARD_GOOGLE_DRIVE;
                break;

            case DROPBOX:
                cardName = CARD_DROPBOX;
                break;

            default:
                return null;
        }

        frame.setTitle(cardName);
        ((CardLayout)frame.pnlCards.getLayout()).show(frame.pnlCards, cardName);

        return frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlMain = new javax.swing.JPanel();
        pnlCards = new javax.swing.JPanel();
        pnlLocal = new com.leong.nimbus.clouds.local.LocalPanel();
        pnlGoogleDrive = new com.leong.nimbus.clouds.google.drive.GDrivePanel();
        pnlDropbox = new com.leong.nimbus.clouds.dropbox.DropboxPanel();
        mnubar = new javax.swing.JMenuBar();
        mnuNimbus = new javax.swing.JMenu();
        mnuOpenNewCloud = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlMain.setMinimumSize(new java.awt.Dimension(400, 300));
        pnlMain.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlCards.setLayout(new java.awt.CardLayout());
        pnlCards.add(pnlLocal, "Local File System");
        pnlCards.add(pnlGoogleDrive, "Google Drive");
        pnlCards.add(pnlDropbox, "Dropbox");

        pnlMain.add(pnlCards, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        mnuNimbus.setText("Nimbus");

        mnuOpenNewCloud.setText("Open New Cloud");
        mnuOpenNewCloud.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuOpenNewCloudActionPerformed(evt);
            }
        });
        mnuNimbus.add(mnuOpenNewCloud);

        mnubar.add(mnuNimbus);

        setJMenuBar(mnubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenNewCloudActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuOpenNewCloudActionPerformed
    {//GEN-HEADEREND:event_mnuOpenNewCloudActionPerformed
        PickCloudFrame.showMe();
    }//GEN-LAST:event_mnuOpenNewCloudActionPerformed

    @Override
    public void setTitle(String title)
    {
        final String APP_NAME = " - Nimbus";

        if (title.endsWith(APP_NAME))
            super.setTitle(title);
        else
            super.setTitle(title + APP_NAME);
    }

    public void runLater()
    {
        Log.entering("runLater");

        java.awt.EventQueue.invokeLater(m_run);
    }

    public void runAndWait()
    {
        Log.entering("runAndWait");

        try
        {
            Log.fine("EventQueue.invokeAndWait(run)");
            java.awt.EventQueue.invokeAndWait(m_run);
        }
        catch (InterruptedException | InvocationTargetException ex)
        {
            Log.throwing("runAndWait", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnuNimbus;
    private javax.swing.JMenuItem mnuOpenNewCloud;
    private javax.swing.JMenuBar mnubar;
    private javax.swing.JPanel pnlCards;
    private com.leong.nimbus.clouds.dropbox.DropboxPanel pnlDropbox;
    private com.leong.nimbus.clouds.google.drive.GDrivePanel pnlGoogleDrive;
    private com.leong.nimbus.clouds.local.LocalPanel pnlLocal;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
