/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leong.nimbus.gui;

import com.leong.nimbus.utils.Logit;
import java.text.MessageFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author henry
 */
public class PickCloudFrame extends javax.swing.JFrame
{

    private static final Logit Log = Logit.create(PickCloudFrame.class.getName());

    /**
     * Creates new form PickCloudFrame
     */
    public PickCloudFrame()
    {
        Log.entering("<init>");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPicker = new javax.swing.JPanel();
        btnLocal = new javax.swing.JButton();
        btnGoogleDrive = new javax.swing.JButton();
        btnDropbox = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nimbus");

        pnlPicker.setMinimumSize(new java.awt.Dimension(400, 300));
        pnlPicker.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlPicker.setLayout(new java.awt.GridBagLayout());

        btnLocal.setText("Local File System");
        btnLocal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLocalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        pnlPicker.add(btnLocal, gridBagConstraints);

        btnGoogleDrive.setText("Google Drive");
        btnGoogleDrive.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/icons/google/drive-32.png")));
        btnGoogleDrive.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGoogleDriveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        pnlPicker.add(btnGoogleDrive, gridBagConstraints);

        btnDropbox.setText("Dropbox");
        btnDropbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDropboxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        pnlPicker.add(btnDropbox, gridBagConstraints);

        getContentPane().add(pnlPicker, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoogleDriveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGoogleDriveActionPerformed
    {//GEN-HEADEREND:event_btnGoogleDriveActionPerformed
        showAndDispose(NimbusFrame.CloudType.GOOGLE_DRIVE);
    }//GEN-LAST:event_btnGoogleDriveActionPerformed

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLocalActionPerformed
    {//GEN-HEADEREND:event_btnLocalActionPerformed
        showAndDispose(NimbusFrame.CloudType.LOCAL_FILE_SYSTEM);
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnDropboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDropboxActionPerformed
    {//GEN-HEADEREND:event_btnDropboxActionPerformed
        showAndDispose(NimbusFrame.CloudType.DROPBOX);
    }//GEN-LAST:event_btnDropboxActionPerformed

    public static void showMe()
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                PickCloudFrame frame = new PickCloudFrame();
                frame.setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            Log.exception(ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PickCloudFrame().setVisible(true);
            }
        });
    }

    protected void showAndDispose(NimbusFrame.CloudType type)
    {
        NimbusFrame frame = NimbusFrame.setupMainPanel(type);

        if (frame != null)
        {
            Log.info("Showing "+type.toString());

            // show it
            frame.runLater();
        }
        else
        {
            Log.warning(MessageFormat.format("Unknown type: {0}", type.toString()));
        }

        // kill me
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDropbox;
    private javax.swing.JButton btnGoogleDrive;
    private javax.swing.JButton btnLocal;
    private javax.swing.JPanel pnlPicker;
    // End of variables declaration//GEN-END:variables
}
