/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leong.nimbus.clouds.dropbox;

import com.dropbox.core.DbxEntry;
import com.leong.nimbus.clouds.dropbox.gui.DropboxFileItem;
import com.leong.nimbus.clouds.dropbox.gui.DropboxFileItemPanelMouseAdapter;
import com.leong.nimbus.clouds.interfaces.CloudPanelAdapter;
import com.leong.nimbus.clouds.interfaces.ICloudProgress;
import com.leong.nimbus.clouds.interfaces.ICloudTransfer;
import com.leong.nimbus.clouds.interfaces.transferadapters.LocalToDropboxTransferAdapter;
import com.leong.nimbus.gui.components.FileItemPanel;
import com.leong.nimbus.gui.helpers.BusyTaskCursor;
import com.leong.nimbus.gui.helpers.DefaultDropTargetAdapter;
import com.leong.nimbus.gui.helpers.ResponsiveTaskUI;
import com.leong.nimbus.gui.helpers.XferHolder;
import com.leong.nimbus.gui.layout.AllCardsPanel;
import com.leong.nimbus.utils.Logit;
import java.awt.Color;
import java.awt.dnd.DropTarget;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author henry
 */
public class DropboxPanel
    extends CloudPanelAdapter<DbxEntry, DropboxController>
{
    private static final Logit Log = Logit.create(DropboxPanel.class.getName());

    /**
     * Creates new form DropboxPanel
     */
    public DropboxPanel()
    {
        super();

        Log.entering("<init>");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnConnect = new javax.swing.JButton();
        pnlFiles = new com.leong.nimbus.gui.layout.AllCardsPanel();

        setLayout(new java.awt.BorderLayout());

        btnConnect.setText("Connect to Dropbox!");
        btnConnect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConnectActionPerformed(evt);
            }
        });
        add(btnConnect, java.awt.BorderLayout.PAGE_START);
        add(pnlFiles, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConnectActionPerformed
    {//GEN-HEADEREND:event_btnConnectActionPerformed
        BusyTaskCursor.doTask(this, new BusyTaskCursor.IBusyTask()
        {
            @Override
            public void run()
            {
                if (m_controller.login(DropboxPanel.this))
                {
                    showFiles(m_controller.getRoot(), false);

                    new DropTarget(pnlFiles, new DefaultDropTargetAdapter()
                    {
                        @Override
                        public boolean onAction_drop(List list)
                        {
                            return DropboxPanel.this.onAction_drop(list);
                        }
                    });

                    showFiles(m_controller.getRoot(), false);
                }
            }
        });
    }//GEN-LAST:event_btnConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private com.leong.nimbus.gui.layout.AllCardsPanel pnlFiles;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initPanel()
    {
        Log.entering("initPanel");
        m_controller = new DropboxController();

        pnlFiles.setProxy(this);
    }

    @Override
    public String getAbsolutePath(DbxEntry item)
    {
        //Log.entering("getAbsolutePath", new Object[]{item.toStringMultiline()});
        return item.path;
    }

    @Override
    public FileItemPanel createFileItemPanel(DbxEntry file)
    {
        FileItemPanel pnl = new FileItemPanel(new DropboxFileItem(file));

        pnl.setBackground(Color.WHITE);

        pnl.addMouseListener(new DropboxFileItemPanelMouseAdapter(file)
        {
            @Override
            public void onOpenFolder(final DbxEntry item)
            {
                responsiveShowFiles(item, true);
            }
        });

        return pnl;
    }

    @Override
    public AllCardsPanel getFilesPanel()
    {
        return pnlFiles;
    }

    @Override
    public XferHolder createXferHolder(java.io.File file)
    {
        final java.io.File inputFile = (java.io.File) file;
        final DbxEntry.File outputFile = m_controller.generateFile(m_currentPath.path, inputFile);
        final FileItemPanel pnl = createFileItemPanel(outputFile);

        pnl.showProgress(true);

        XferHolder<java.io.File, DbxEntry.File> holder = new XferHolder<>();
        holder.xfer = new LocalToDropboxTransferAdapter(inputFile, outputFile);
        holder.pnl = pnl;

        return holder;
    }

}
